[tool.black]
line-length = 80
target-version = ["py37"]
exclude = '''
/(
  \.toml
  | \.sh
  | \.git
  | \.ini
  | \.md
  | \.ipynb
  | environ
  | \*cache
  | \*.ipynb_checkpoints
  | \*.DS_Store
  | \*.idea
)/
'''

[tool.pydocstyle]
match-dir='(?!environ|tests|\.).*'
match='(?!test_|__init).*\.py'
