[tool.black]
line-length = 80
target-version = ["py37"]
exclude = '''
/(
  \.toml
  | \.sh
  | \.git
  | \.ini
  | \.md
  | environ
  | \*.DS_Store
  | \*.idea
)/
'''

[tool.pydocstyle]
match-dir='[^.|^environ].*'
match='[^__init__].*'
